### ISSUE TITLE
Latest update broke composer?

### ISSUE THREAD

**Issue by mlantz7** [shinsenter/php#85] opened 2024-07-29 17:56 UTC
Hi there,

It seems something changed over the weekend that broke the package. It appears that "composer install" no longer runs automatically in the container, which broke our deployment process.

Any idea?

**Comment by mlantz7** [comment] 2024-07-29 19:35
I think there are now some other issues as well...

I see crontab is working, but now I am seeing this in the logs:

```
PHP Warning:  PHP Startup: session.configuration 'session.sid_length' must be between 22 and 256. in Unknown on line 0
PHP Warning:  PHP Startup: session.configuration 'session.sid_bits_per_character' must be between 4 and 6. in Unknown on line 0
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 20480 bytes) in /srv/www/vendor/google/apiclient/src/Collection.php on line 97
```

I do use set some PHP_ env variables in the Dockerfile, and I do see that the values I set for them are correct when running `php-envvars`. But maybe they are not properly being set in PHP?

**Comment by shinsenter** [comment] 2024-07-29 22:07
@mlantz7 

I’m very sorry for the issues you are experiencing. I will check the information you have provided and fix it soon, but could you let me know which Docker images you are using?

**Comment by mlantz7** [comment] 2024-07-29 22:16
7.4-fpm-apache

Also, cron is giving me these errors every time it runs in syslogd/errors/current:

`authpriv.err: Jul 29 17:09:01 CROND[13464]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directory`

This is my Dockerfile as of now:

```
FROM shinsenter/php:7.4-fpm-apache

# Install useful / needed packages
RUN apt-get update && apt-get install -y jq nano

# Add needed PHP modules
RUN phpaddmod bz2 gmp mcrypt sockets

# Control your timezone
ENV TZ="America/Chicago"

# sets GID and UID (done in compose file)
#ENV APP_UID=992
#ENV APP_GID=992

# Sets needed paths for app
ENV APP_PATH="/srv/www"
ENV DOCUMENT_ROOT="/public_html"

# Disable composer install in package (handled in app init)
ENV DISABLE_AUTORUN_COMPOSER_INSTALL=1

# Set some PHP variables
ENV ALLOW_RUNTIME_PHP_ENVVARS=1
ENV PHP_SESSION_SERIALIZE_HANDLER="php"
ENV PHP_SESSION_SID_LENGTH="26"
ENV PHP_SESSION_SID_BITS_PER_CHARACTER="5"
ENV PHP_SESSION_GC_PROBABILITY=0
ENV PHP_OPCACHE_ENABLE_CLI=0

# add startup files
ADD ./deploy/config/00-init /startup/00-init
RUN chmod +x /startup/00-init

WORKDIR $APP_PATH
```

Today I added the DISABLE_AUTORUN_COMPOSER_INSTALL and ALLOW_RUNTIME_PHP_ENVVARS to overcome some of the issues I was having. I now run "composer install" in my startup script (00-init).

But yeah this is causing all kinds of issues for us today. I really wish there was a way to ensure new versions don't automatically break our deployments with versioning of some sort.

**Comment by mlantz7** [comment] 2024-07-29 22:32
So it looks like `/etc/default/locale` is currently misnamed as `/etc/default/localenv`, which is causing the above problem. That also is likely causing the other issues with PHP vars not being set right huh?

**Comment by shinsenter** [comment] 2024-07-29 23:28
@mlantz7 

Thank you very much for the in-depth investigations. I apologize for the recent typo I made in `/etc/default/locale`. I will promptly correct it and rebuild all the Docker images as soon as possible, though it will take a few hours.

In the meantime, please try using other tags from the repo below to access previous builds of the `shinsenter/php:7.4-fpm-apache`.
https://hub.docker.com/r/shinsenter/php-archives/tags?name=7.4-fpm-apache

I hope this will help you get a stable build for production.

**Comment by mlantz7** [comment] 2024-07-29 23:35
No worries. Stuff happens.

So just for clarity, are there 2 issues to resolve?

1) Composer install not running when it should
2) /etc/default/locale typo?

I am guessing #2 will fix other related issues other than cron, like the PHP vars not being properly set? I guess my use of `ALLOW_RUNTIME_PHP_ENVVARS` fixed it in some partial way, but should not be necessary if we are not trying to change those vars from within the container right?

And thanks for the tag info - I was not aware you had implemented that. It is very helpful - although then I will have to keep an closer eye out for bug fixes and such. :)

**Comment by shinsenter** [comment] 2024-07-29 23:43
@mlantz7 

Based on my current understanding, I believe the typo in `/etc/default/locale` only affects certain Debian programs. The `/etc/default/locale` file contains a copy of the environment variables **when the container is started** to ensure that other programs within the container share the same set of environment variables related to PHP settings.

When running commands in the Dockerfile, since this file and other PHP dynamic config files are not yet created, PHP and other programs will essentially load the default settings. Therefore, fixing item number 2 might not resolve the composer error when it fails to run in the Dockerfile during your container builds (I need more error logs for deeper investigation).

However, I believe that correcting the typo in `/etc/default/locale` will fix the crontab errors.

**Comment by shinsenter** [comment] 2024-07-29 23:56
@mlantz7

The release versions on this GitHub repository don't guarantee that Docker images built from the same source code will always be identical.

This is because my Docker images are built on PHP base images, meaning that PHP binaries, Debian/Alpine packages, Composer versions, etc. can change with each build. I've mentioned that I build my Docker images daily to include the latest security patches and software updates.

https://github.com/shinsenter/php/blob/5.x/README.md#stable-image-tags

> We build new Docker images daily to ensure they stay up-to-date with the latest upstream updates for PHP, base OS, Composer, etc. The images in this repo are regularly updated under the same tag names.
>
> For stable versions you can depend on in production, we also apply version tags on another repository.
>
> > 👉🏻 View Stable Tags: https://hub.docker.com/r/shinsenter/php-archives/tags
This way, you get frequently updated images under static tags, providing both the latest code and production stability.

This means projects building containers using any tags on the main repository might suddenly stop working one day. This issue is similar to using any official Docker image with the "latest" tag. To mitigate this, I've created separate archives for my Docker images based on their build date. You can consider the images on the main repository always "beta".

**Comment by shinsenter** [comment] 2024-07-30 06:22
@mlantz7 
The docker images for `shinsenter/php:7.4-fpm-apache` have been updated.

https://hub.docker.com/r/shinsenter/php-archives/tags?page=&page_size=&ordering=&name=20240730-7.4-fpm-apache

Could you please help me check again to see if your issue has been resolved?

**Comment by mlantz7** [comment] 2024-07-30 17:31
So the locale file is now correct and is working fine. However, "composer install" still does not happen.

**Comment by shinsenter** [comment] 2024-07-31 00:04
@mlantz7 
When you run `composer install`, are there any specific error messages? Or any indications that it did not run completely?

**Comment by mlantz7** [comment] 2024-07-31 01:48
Sorry, maybe the issue is unclear.

I can run `composer install` manually and there is no problem. In fact, that is what I had to change to once the normal functionality broke. Now I run it as part of my init processes.

The issue is that it used to run on its own automatically (before I added the `DISABLE_AUTORUN_COMPOSER_INSTALL` parameter). When I removed the parameter and tested again today, it did not run automatically as it used to.

Hopefully that makes things more clear.

**Comment by shinsenter** [comment] 2024-07-31 03:14
@mlantz7 

Currently, I am still unable to reproduce your specific case. I tested it on my computer with a directory that has the composer.json file (no vendor directory), and when starting the container, `composer install` was automatically run without any issues.

I will continue to spend time investigating further to see if there are any other possible causes, as it is very difficult without any error messages or useful debug information in your case.

**Comment by shinsenter** [comment] 2024-08-05 11:07
@mlantz7 

Sorry to keep you waiting, but can I ask you to test composer install again with the latest docker images? I hope this can solve your problem.

**Comment by shinsenter** [comment] 2024-08-14 14:26
I will close this issue due to no updates. If you have any other concerns, please feel free to create a new issue.

**Closed by shinsenter** 2024-08-14 14:26 UTC
